name: 'kubernetes-name-sanitize'
description: 'Sanitize a string for kubernetes names'
inputs:
  input:
    description: 'Input'
    required: true
    default: ''
  multiple:
    description: 'Multiple inputs, comma separated'
    required: false
    default: false
    type: boolean
outputs:
  output: # id of output
    description: 'The sanitized string'
runs:
  using: 'node20'
  main: 'dist/index.js'